<?php foreach ($block->getBookData() as $item): ?>
    <form action="<?php echo $block->getUrl('books/index/save'); ?>" method="post"
          enctype="multipart/form-data">
        <table>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Author</th>
                <th>Total pages</th>
            </tr>
            <tr>
                <th>
                    <div class="input-group">
                        <input name="book_id" type="text" class="form-control"
                               value="<?php echo $item['book_id']; ?>" readonly>
                    </div>
                </th>
                <br>
                <th>
                    <div class="input-group">
                        <input name="title" type="text" class="form-control" placeholder="Book title"
                               value="<?php echo $item['title']; ?>">
                    </div>
                </th>
                <br>
                <th>
                    <div class="input-group">
                        <input name="author" type="text" class="form-control" placeholder="Author"
                               value= <?php echo $item['author'] ?>>
                    </div>
                </th>
                <br>
                <th>
                    <div class="input-group">
                        <input name="total_pages" type="number" class="form-control" placeholder="Total Pages"
                               value= <?php echo $item['total_pages'] ?>>
                    </div>
                </th>
            </tr>
        </table>
        <br>
        <div class="form-group">
            <div>
                <button type="submit">Update book</button>
            </div>
        </div>
    </form>
<?php endforeach; ?>
