<?php foreach ($block->getBookData() as $item): ?>
    <form action="<?php echo $block->getUrl('books/index/save'); ?>" method="post" enctype="multipart/form-data">
        <div class="input-group">
            <input name="book_id" type="text" class="form-control"
                   value="<?php echo $item['book_id']; ?>" readonly>
        </div>
        <br>
        <div class="input-group">
            <input name="title" type="text" class="form-control" placeholder="Book title"
                   value="<?php echo $item['title']; ?>">
        </div>
        <br>
        <div class="input-group">
            <input name="author" type="text" class="form-control" placeholder="Author"
                   value= <?php echo $item['author'] ?>>
        </div>
        <br>
        <div class="input-group">
            <input name="total_pages" type="number" class="form-control" placeholder="Total Pages"
                   value= <?php echo $item['total_pages'] ?>>
        </div>
        <br>
        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <button type="submit" class="btn btn-primary">Update book</button>
            </div>
        </div>
    </form>
<?php endforeach; ?>

