<table>
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Total Pages</th>
    </tr>
    <?php
    /** @var Encomage\Book\Block\Index $block */
    foreach ($block->getResult() as $item):
        ?>
        <tr>
            <td>
                <?php echo $item->getId(); ?>
            </td>
            <td>
                <?php echo $item->getTitle(); ?>
            </td>
            <td>
                <?php echo $item->getTotalPages(); ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
