<table>
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Author</th>
        <th>Total Pages</th>
        <th></th>
        <th></th>
    </tr>
    <?php
    /** @var Encomage\Book\Block\Index $block */
    foreach ($block->getResult() as $item):
        ?>
        <tr>
            <td>
                <?php echo $item->getId(); ?>
            </td>
            <td>
                <?php echo $item->getTitle(); ?>
            </td>
            <td>
                <?php echo $item->getAuthor(); ?>
            </td>
            <td>
                <?php echo $item->getTotalPages(); ?>
            </td>
            <td>
                <a class="action primary" href="<?php echo($block->getEditUrl() . 'id/' . $item->getId()); ?>">Edit
                    book</a>
            </td>
            <td>
                <a class="action primary" href="<?php echo($block->getDeleteUrl() . 'id/' . $item->getId()); ?>">Delete
                    book</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<br>
<a class="action primary" href="<?php echo $block->getInsertUrl(); ?>">Add new book</a>
